### ISSUE TITLE
The workflow list also the headlines

### ISSUE THREAD

**Issue by nilshae** [nikitavoloboev/alfred-awesome-lists#2]
The workflow list also the headlines (like #Editors or #Platforms) from the readme.md.

![alfred-awesome-lists_issue](https://user-images.githubusercontent.com/9952617/32296755-5b12a286-bf4d-11e7-82de-e1a044d3ab33.gif)

I think the bug is in the [markdown-parser](https://github.com/nikitavoloboev/markdown-parser/commit/3b060d4213cd078d3dbaeeced576d0affb4fc825) so I guess the Issue is probably as relevant over there.

**Comment by nikivdev** [comment]
Yeah I know about it. Sorry for that.

I am working on a new version that will fix it and will also let you go `inside` any of the awesome lists and see contents of each one from Alfred.

Hope to release that soon. Also, awesome background you have there. 🙂

**Comment by nikivdev** [comment]
This is fixed in the new update.
