### ISSUE TITLE
Appending `#readme` twice

### ISSUE THREAD

**Issue by azdanov** [nikitavoloboev/alfred-awesome-lists#7]
Workflow stopped working after a while and started to misbehave by appending `#readme` once more at the end of `{query}`.

<img width="192" alt="screen shot 2018-07-09 at 14 24 48" src="https://user-images.githubusercontent.com/6123841/42447853-f1d2ee24-8383-11e8-8a5c-10d632807681.png">

Is it something related to this line?

https://github.com/nikitavoloboev/alfred-awesome-lists/blob/713fd69b4c5a6f2d183189311823e7be89200d3c/search.go#L23

**Comment by nikivdev** [comment]
> Is it something related to this line?

Yeah it is. I know of the issue. I just wanted to release a fix with caching done. Will release a fix in the evening.

**Comment by nikivdev** [comment]
[Released new version](https://github.com/nikitavoloboev/alfred-awesome-lists/releases/latest) with caching & fixed links.
